(() => {
  let controls = null;
  let scanning = false;
  let zxingPromise = null;
  let detectedBarcode = '';
  const $ = (id) => document.getElementById(id);

  function ensureUI() {
    if ($('barcodeLiveView')) return;
    const view = document.createElement('section');
    view.id = 'barcodeLiveView'; view.className = 'barcode-live-view'; view.hidden = true;
    view.innerHTML = `<div class="barcode-live-head"><button id="barcodeLiveBack" type="button" class="ghost">‹ Retour</button><strong>Scanner le code-barres</strong></div><div class="barcode-camera-frame"><video id="barcodeLiveVideo" autoplay playsinline muted></video><div class="barcode-target" aria-hidden="true"><span></span></div></div><div id="barcodeDetectedBox" hidden style="margin:14px 0;padding:12px;border-radius:14px;background:#e8f3f1;text-align:center"><small style="display:block;color:#607874">✓ Code-barres détecté</small><strong id="barcodeDetectedValue" style="font-size:20px;letter-spacing:.06em"></strong></div><p id="barcodeLiveStatus" class="barcode-live-status">Place le code-barres dans le cadre.</p><p class="muted small">La détection est automatique. Pas besoin de prendre une photo.</p><div id="barcodeUnknownActions" hidden style="display:grid;gap:8px"><button id="barcodePhotoFallback" type="button">📷 Photographier le produit</button><button id="barcodeNameBtn" type="button" class="ghost">⌨️ Saisir le nom</button><button id="barcodeVoiceBtn" type="button" class="ghost">🎙️ Dicter le nom</button></div>`;
    document.querySelector('.catalog-sheet-card')?.appendChild(view);
    $('barcodeLiveBack').addEventListener('click', stopLiveScanner);
    $('barcodePhotoFallback').addEventListener('click', openPhotoFallback);
    $('barcodeNameBtn').addEventListener('click', enterName);
    $('barcodeVoiceBtn').addEventListener('click', dictateName);
  }
  function setStatus(text){ if($('barcodeLiveStatus')) $('barcodeLiveStatus').textContent=text; }
  function showDetected(code){ detectedBarcode=code; $('barcodeDetectedValue').textContent=code; $('barcodeDetectedBox').hidden=false; sessionStorage.setItem('whatzabi_pending_barcode',code); }
  function loadZXing(){ if(window.ZXingBrowser)return Promise.resolve(window.ZXingBrowser);if(zxingPromise)return zxingPromise;zxingPromise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://unpkg.com/@zxing/browser@0.2.1';s.async=true;s.onload=()=>window.ZXingBrowser?resolve(window.ZXingBrowser):reject(new Error('Lecteur indisponible'));s.onerror=()=>reject(new Error('Lecteur indisponible'));document.head.appendChild(s)});return zxingPromise }
  function normalizeCode(v){const code=String(v||'').replace(/\D/g,'');return code.length>=8&&code.length<=14?code:''}
  async function lookup(code){showDetected(code);setStatus('Recherche du produit…');navigator.vibrate?.(80);const token=localStorage.getItem('whatzabi_token')||'';const r=await fetch(`/pwa/catalog/barcode/${encodeURIComponent(code)}`,{headers:{Authorization:`Bearer ${token}`}});let body=null;try{body=await r.json()}catch{}if(!r.ok)throw new Error(body?.detail||'Produit absent du référentiel.');return body}
  function renderResult(body){const cs=body?.candidates||[],list=$('catalogCandidateList');list.innerHTML='';$('catalogResultCount').textContent=cs.length?`${cs.length} produit détecté`:'Code reconnu';cs.forEach(c=>{const card=document.createElement('article');card.className='catalog-candidate';const h=document.createElement('h3');h.textContent=c.name||'Produit';card.appendChild(h);const meta=document.createElement('div');meta.className='catalog-meta';[c.brand,c.packaging,c.barcode&&`EAN : ${c.barcode}`].filter(Boolean).forEach(v=>{const chip=document.createElement('span');chip.className='catalog-chip';chip.textContent=v;meta.appendChild(chip)});card.appendChild(meta);list.appendChild(card)});$('barcodeLiveView').hidden=true;$('catalogResults').hidden=false;$('catalogModes').hidden=true;$('catalogCapture').hidden=true}
  async function onDetected(raw){if(!scanning)return;const code=normalizeCode(raw);if(!code)return;scanning=false;stopCameraOnly();try{renderResult(await lookup(code))}catch(e){showDetected(code);setStatus('Produit inconnu de nos référentiels. Complète son identité pour que Whatzabi le reconnaisse la prochaine fois.');$('barcodeUnknownActions').hidden=false}}
  async function startZXing(){const ZXing=await loadZXing();const reader=new ZXing.BrowserMultiFormatReader();controls=await reader.decodeFromConstraints({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}}},$('barcodeLiveVideo'),result=>{if(result)onDetected(result.getText?result.getText():result.text)})}
  async function startLiveScanner(){ensureUI();detectedBarcode='';sessionStorage.removeItem('whatzabi_pending_barcode');$('barcodeDetectedBox').hidden=true;$('barcodeUnknownActions').hidden=true;$('catalogModes').hidden=true;$('catalogCapture').hidden=true;$('catalogResults').hidden=true;$('barcodeLiveView').hidden=false;setStatus('Ouverture de la caméra…');scanning=true;try{await startZXing();setStatus('Place le code-barres dans le cadre. Détection automatique.')}catch{scanning=false;stopCameraOnly();setStatus('Caméra scanner indisponible. Reviens en arrière et utilise Photo produit.')}}
  function stopCameraOnly(){try{controls?.stop?.()}catch{}controls=null;const video=$('barcodeLiveVideo');if(video?.srcObject){video.srcObject.getTracks().forEach(t=>t.stop());video.srcObject=null}}
  function stopLiveScanner(){scanning=false;stopCameraOnly();if($('barcodeLiveView'))$('barcodeLiveView').hidden=true;$('catalogModes').hidden=false;$('catalogCapture').hidden=true;$('catalogResults').hidden=true}
  function openPhotoFallback(){stopCameraOnly();$('barcodeLiveView').hidden=true;$('catalogModes').hidden=false;$('catalogCapture').hidden=true;document.querySelector('[data-catalog-source="product"]')?.click();setStatus('')}
  function saveManualDraft(name,source){const clean=String(name||'').trim();if(!clean)return;const draft={source:'barcode',candidates:[{name:clean,barcode:detectedBarcode,confidence:1}],matches:{},requires_confirmation:true,identification_source:source};sessionStorage.setItem('whatzabi_catalog_draft',JSON.stringify(draft));sessionStorage.setItem('whatzabi_pending_barcode',detectedBarcode);$('barcodeLiveView').hidden=true;renderResult(draft)}
  function enterName(){const name=window.prompt(`Nom du produit\nCode-barres : ${detectedBarcode}`,'');if(name)saveManualDraft(name,'manual')}
  function dictateName(){const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SpeechRecognition){setStatus('La dictée directe n’est pas disponible ici. Utilise “Saisir le nom” ou photographie le produit.');return}const r=new SpeechRecognition();r.lang='fr-FR';r.interimResults=false;r.maxAlternatives=1;setStatus('🎙️ Dis le nom du produit…');r.onresult=e=>saveManualDraft(e.results?.[0]?.[0]?.transcript||'','voice');r.onerror=()=>setStatus('Je n’ai pas compris. Réessaie ou saisis le nom.');r.start()}
  document.addEventListener('click',e=>{const b=e.target.closest('[data-catalog-source="barcode"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();startLiveScanner()},true);
  document.addEventListener('click',e=>{if(e.target.closest('#catalogCloseBtn')||e.target.closest('#catalogRestartBtn')){scanning=false;stopCameraOnly()}},true);
})();